### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by jhoelzl** [mhauri/generate-modman#1]
Hello,

when i go to my module folder to create a modman file with the command  

```
generate-modman
```

i get these warnings:

> find: warning: you have specified the -mindepth option after a non-option argument -type, but options are not positional (-mindepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
> 
> find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
> 
> find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
> 
> find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.

**Comment by mhauri** [comment]
Hi @jhoelzl 
Will have a look and update the script as soon as possible.

**Comment by mhauri** [comment]
Fixed
